//
// Created by kamil on 14.11.2025.
//

#ifndef SUDOKUSOLVER_GLOBAL_DEFINES_H
#define SUDOKUSOLVER_GLOBAL_DEFINES_H

namespace Consts {
    constexpr int SUDOKU_DIMENSION_SIZE = 9;
    constexpr int SUDOKU_BOARD_SIZE = SUDOKU_DIMENSION_SIZE * SUDOKU_DIMENSION_SIZE;
}

#endif //SUDOKUSOLVER_GLOBAL_DEFINES_H